INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM01/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM02/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM03/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM04/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM05/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNHCM06/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNBRVT/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNBD/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNBP/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNLD/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNNT/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNBT/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNTN/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNLA/Lists/Announcements/AllItems.aspx', 0);
INSERT INTO PORTALANNOUNCEMENTCATEGORY(AUTHORINGTEMPLATEID, DEPARTMENTID, URL, STATUS) VALUES(51, , 'http://10.151.70.91/CNDN/Lists/Announcements/AllItems.aspx', 0);

