ALTER TABLE PortalContent MODIFY COLUMN XmlData TEXT;

ALTER TABLE PortalCategory ADD COLUMN PrefixUrl  CHAR(255);


SHOW CREATE TABLE PortalContent;

ALTER TABLE PortalContent MODIFY COLUMN Title varchar(255) NOT NULL;

ALTER TABLE PortalContent ADD CONSTRAINT U_CONTENT_TITLE UNIQUE (Title);

ALTER TABLE PortalContent MODIFY COLUMN categoryID double(19,0) NOT NULL;

ALTER TABLE PortalContent ADD CONSTRAINT fk_content_category FOREIGN KEY (categoryID) REFERENCES PortalCategory(categoryID);

ALTER TABLE PortalCategory DROP FOREIGN KEY `FK86B49AA5EA6EFFD`;

ALTER TABLE PortalCategory MODIFY COLUMN ParentRootID double(19,0) DEFAULT NULL;

ALTER TABLE PortalCategory DROP FOREIGN KEY `portalcategory_ibfk_1`;

ALTER TABLE PortalCategory ADD CONSTRAINT fk_category_parent_category FOREIGN KEY (parentCatID) REFERENCES PortalCategory(categoryID) ON DELETE NO ACTION  ON UPDATE NO ACTION ;

-- ADD EVENT CONTENT ----
ALTER TABLE PortalAuthoringTemplate ADD COLUMN `IsEvent` varchar(8) DEFAULT 'N';

ALTER TABLE PortalContent DROP COLUMN beginDate;

ALTER TABLE PortalContent DROP COLUMN endDate;

ALTER TABLE PortalContent ADD COLUMN BeginDate DATETIME DEFAULT NULL;

ALTER TABLE PortalContent ADD COLUMN EndDate DATETIME DEFAULT NULL;

--  CONVERT DATABASE TO UTF8 --
ALTER DATABASE NttPortal CHARACTER SET UTF8 COLLATE utf8_unicode_ci;

ALTER TABLE PortalContent CONVERT TO CHARACTER SET UTF8 COLLATE utf8_general_ci;

ALTER TABLE PortalAuthoringTemplate ADD COLUMN PrefixUrl VARCHAR(255) DEFAULT NULL;

ALTER TABLE PortalUser DROP FOREIGN KEY `FK86D8AE77E48B3625`;

