CREATE TABLE PortalFeedbackCategory (
  FeedbackCategoryID NUMBER PRIMARY KEY,
  Name VARCHAR(255),
  Description VARCHAR(512),
  CONSTRAINT PortalFeedbackCategory_UQ UNIQUE (Name)
);

CREATE SEQUENCE PortalFeedbackCategory_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE PortalFeedback (
  FeedbackID NUMBER PRIMARY KEY,
  DepartmentID NUMBER NOT NULL,
  FeedbackCategoryID NUMBER NOT NULL,
  Title VARCHAR(512),
  Content CLOB,
  CreatedBy NUMBER NOT NULL,
  CreatedDate TIMESTAMP NOT NULL,
  Status NUMBER(1, 0)
);

ALTER TABLE PortalFeedback ADD CONSTRAINT PORTALFEEDBACK_CATEGORY_FK FOREIGN KEY(FeedbackCategoryID) REFERENCES PortalFeedbackCategory(FeedbackCategoryID);
ALTER TABLE PortalFeedback ADD CONSTRAINT PORTALFEEDBACK_DEPT_FK FOREIGN KEY(DepartmentID) REFERENCES PortalDepartment(DepartmentID);
ALTER TABLE PortalFeedback ADD CONSTRAINT PORTALFEEDBACK_USER_FK FOREIGN KEY(CreatedBy) REFERENCES PortalUser(UserID);


CREATE SEQUENCE PortalFeedback_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE PortalFeedbackReply (
  FeedbackReplyID NUMBER PRIMARY KEY,
  FeedbackID NUMBER NOT NULL,
  Content CLOB,
  CreatedBy NUMBER NOT NULL,
  CreatedDate TIMESTAMP NOT NULL
);

ALTER TABLE PortalFeedbackReply ADD CONSTRAINT PORTALFEEDBACKREPLY_FB_FK FOREIGN KEY(FeedbackID) REFERENCES PortalFeedback(FeedbackID);
ALTER TABLE PortalFeedbackReply ADD CONSTRAINT PORTALFEEDBACKREPLY_USER_FK FOREIGN KEY(CreatedBy) REFERENCES PortalUser(UserID);

CREATE SEQUENCE PortalFeedbackReply_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

ALTER TABLE PORTALUSER
ADD
(
  IsShopper INT null
);


ALTER TABLE PORTALSMS
ADD
(
  FeedbackID NUMBER NULL
);
ALTER TABLE PORTALSMS ADD CONSTRAINT FK_SMS_Feedback FOREIGN KEY (FeedbackID) REFERENCES PortalFeedback(FeedbackID) ON DELETE CASCADE ;

ALTER TABLE PORTALDEPARTMENT
ADD
(
  Mobile VARCHAR(20) NULL
);