ALTER TABLE PORTALAUTHORINGTEMPLATE
ADD
(
  HasThumbnail VARCHAR(1) DEFAULT 'N',
  HasHotItem VARCHAR(1) DEFAULT 'N'
);
UPDATE PORTALAUTHORINGTEMPLATE SET HasHotItem = 'Y' WHERE Code = 'tin-tuc';

UPDATE PORTALAUTHORINGTEMPLATE SET HasThumbnail = 'Y' WHERE Code = 'tin-tuc';
UPDATE PORTALAUTHORINGTEMPLATE SET HasThumbnail = 'Y' WHERE Code = 'tin-quan-trong';
UPDATE PORTALAUTHORINGTEMPLATE SET HasThumbnail = 'Y' WHERE Code = 'thong-bao';

ALTER TABLE
   MVNForumThread
ADD
(
  ThreadShowVMS number(2,0) DEFAULT 1
);

UPDATE MVNForumThread SET ThreadShowVMS = 1;