CREATE TABLE PortalAnnouncementCategory (
  AnnouncementCategoryID NUMBER PRIMARY KEY,
  AuthoringTemplateID NUMBER NOT NULL,
  DepartmentID NUMBER NOT NULL,
  URL VARCHAR(512),
  Status NUMBER(1, 0)
);

CREATE SEQUENCE PortalAnnouncementCategory_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
