CREATE TABLE PortalSMS (
  SmsID NUMBER PRIMARY KEY,
  ContentID NUMBER NOT NULL,
  MobileNumber VARCHAR2(20 byte) NOT NULL,
  SmsContent VARCHAR2 (100 byte) NOT NULL,
  Status NUMBER(1, 0),
  CreatedDate TIMESTAMP NOT NULL,
  SentDate TIMESTAMP
);

ALTER TABLE PortalSMS ADD CONSTRAINT FK_SMS_Content FOREIGN KEY (ContentID) REFERENCES PortalContent(ContentID);
CREATE SEQUENCE PortalSMS_SEQ  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;