ALTER TABLE PORTALCONTENT
ADD
(
  CREATEDBY number(19,0) null,
  MODIFIEDBY number(19,0) null
);

ALTER TABLE PORTALCONTENT
ADD CONSTRAINT FK_CONTENT_USER_CREATEDBY
FOREIGN KEY (CREATEDBY)
REFERENCES PORTALUSER(USERID);
ALTER TABLE PORTALCONTENT
ADD CONSTRAINT FK_CONTENT_USER_MODIFIEDBY
FOREIGN KEY (MODIFIEDBY)
REFERENCES PORTALUSER(USERID);